apiVersion: v1
data:
  config.env: ENVIRONMENT=production
kind: ConfigMap
metadata:
  name: nginx-config-kc629fh78g
  namespace: production
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
    project: oicndi2020
  name: nginx
  namespace: production
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: nginx
    project: oicndi2020
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    project: oicndi2020
  name: nginx
  namespace: production
spec:
  replicas: 3
  selector:
    matchLabels:
      project: oicndi2020
  template:
    metadata:
      labels:
        project: oicndi2020
    spec:
      containers:
      - image: nginx:1.14.2
        name: nginx
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: 256Mi
