apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base/
namespace: production

patchesStrategicMerge:
  - set_memory.yaml

configMapGenerator:
  - name: nginx-config
    files:
      - config.env
