apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base/
namespace: staging

patchesStrategicMerge:
  - replicas.yaml

configMapGenerator:
  - name: nginx-config
    files:
      - config.env
